import { useEffect, useState } from "react";
import Head from "next/head";
import OpenWeatherService from "@/services/OpenWeatherService";
import { OpenWeatherApiResponse } from "@/services/types";
import SearchBox from "@/components/ui/SearchBox";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [weatherData, setWeatherData] = useState<OpenWeatherApiResponse | null>(
    null
  );

  useEffect(() => {
    setIsLoading(true);
    OpenWeatherService.getWeatherForecastByCity()
      .then((data) => {
        setWeatherData(data);
        setIsLoading(false);
      })
      .catch((error) => {
        setIsLoading(false);
        setError(error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div data-testid="title">Hello World</div>
        <SearchBox />
        <div>
          {isLoading && !weatherData ? (
            "loading..."
          ) : (
            <code>{JSON.stringify(weatherData)}</code>
          )}
        </div>
      </main>
    </>
  );
}
