import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import OpenWeatherService from "@/services/OpenWeatherService";
import { OpenWeatherApiResponse } from "@/services/types";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [weatherData, setWeatherData] = useState<OpenWeatherApiResponse | null>(
    null
  );

  useEffect(() => {
    setIsLoading(true);
    OpenWeatherService.getWeatherForecastByCity().then((data) => {
      setWeatherData(data);
      setIsLoading(false);
    });
  }, []);
  
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div data-testid="title">Hello World</div>
        <div>
          {isLoading && !weatherData ? (
            "loading..."
          ) : (
            <code>{JSON.stringify(weatherData)}</code>
          )}
        </div>
      </main>
    </>
  );
}
