name: main-workflow
on: [push]
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17.2' 
      - run: yarn install
      - run: yarn lint